# docker stack deploy -c docker-compose.yml bindman-dns-agent
version: '3.5'

services:

  bind:
    image: abilioesteves/bind9:0.0.3
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - data:/keys
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s

  manager:
    depends_on: 
      - "bind"
    image: abilioesteves/bindman-dns-bind9:0.0.3
    volumes:
      - data:/data
    ports:
      - 7070:7070/tcp
    environment:
      - BINDMAN_NAMESERVER_ADDRESS=bind
      - BINDMAN_NAMESERVER_KEYFILE=Ktest.com.+157+50086.key
      - BINDMAN_NAMESERVER_ZONE=test.com
      - BINDMAN_DNS_REMOVAL_DELAY=1
      - BINDMAN_MODE=DEBUG
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s
  
  listener:
    depends_on: 
      - "manager"
    image: abilioesteves/bindman-dns-swarm-listener:0.0.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.38
      - BINDMAN_DNS_MANAGER_ADDRESS=manager:7070
      - BINDMAN_REVERSE_PROXY_ADDRESS=0.0.0.0
      - BINDMAN_DNS_TAGS=internal,intranet,internet
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s

volumes:
  data:
